### PR TITLE
Added Support For fastify

### PR DESCRIPTION
**Pull request by inaseem**
Hi,
This is a pull request to support fastify server.

Following is the change
```js
sendResponses_(requestSource) {
    let responseJson = this.responseJson_;

    if (this.agent.followupEvent_) {
      responseJson = responseJson || {};
      responseJson.followupEventInput = this.agent.followupEvent_;
    }

    if (!responseJson) {
      error(`No responses defined for platform: ${requestSource}`);
      this.agent.response_.status(ERROR_HTTP_STATUS_CODE).send(`No responses defined for platform: ${requestSource}`);
    } else {
      responseJson.outputContexts = this.agent.context.getV2OutputContextsArray();
      if (this.agent.endConversation_) {
        responseJson.triggerEndOfConversation = this.agent.endConversation_;
      }
      debug('Response to Dialogflow: ' + JSON.stringify(responseJson));
      if (typeof this.agent.response_.json !== 'undefined') {
        this.agent.response_.json(responseJson);
      } else {
        this.agent.response_.send(responseJson);
      }
    }
  }
```

### CODE REVIEW

**Comment by naseemali925** [comment]
`I signed it!`

**Comment by tjmonsi** [comment]
anyone? When will this be part of dialogflow? We are currently using Fastify as Fulfillment and this is a major blockage for us.

**Comment by inaseem** [comment]
Hi, @tjmonsi I am not sure if they are even maintaining this node js fulfilment library. If you want this to work you can directly make this change to your local copy.

**Comment by tjmonsi** [comment]
Ohh i see. Thanks thanks

**Pull request closed without merging**
