### PR TITLE
Handle case where `detectIntentRequest.payload` is null

### PR DESCRIPTION
**Pull request by aviv-ebates**
See #15. 
If `originalDetectIntentRequest` does not have a value for `payload`, this line throws `Cannot read property 'source' of undefined` - check against it. 

I believe this happens if the chat client sends a funny OriginalDetectIntent, and the server just sends it on the the fulfillment webhook.

### CODE REVIEW

**Comment by aviv-ebates** [comment]
I signed it!

**Comment by c4ndybar** [comment]
If you have migrated your Dialogflow App to V2 but still try to make V1 api requests, you will encounter this issue with every webhook request.  This definitely makes it harder to migrate to V2.

**Comment by aviv-ebates** [comment]
If anyone is wondering, I tried to resolve a conflict using the Github web ui, and it appears it also added all of `master` to the PR while at it. Which broke the CLA tester.

**Comment by matthewayne** [comment]
Thanks for the pull request.  Since the only change left in this pull request is from aviv-ebates and they have signed the CLA I've merged this.  Thanks!

**Pull request merged**
